using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace SplitAndMerge
{
    /// <summary>
    /// Delegate shape shared by every precompiled CSCS function.
    /// </summary>
    public delegate Variable PrecompiledFunction(
        Interpreter interpreter,
        List<string> varStr, List<double> varNum, List<int> varInt,
        List<List<string>> varArrStr, List<List<double>> varArrNum, List<List<int>> varArrInt,
        List<Dictionary<string, string>> varMapStr, List<Dictionary<string, double>> varMapNum,
        List<Variable> varVar);

    /// <summary>
    /// Holds cfunction implementations that were compiled ahead of time, by name.
    ///
    /// Runtime code generation is impossible under AOT (iOS most notably, where the
    /// platform forbids it outright). Registering an implementation here lets a cfunction
    /// run on those targets: Precompiler.Compile() finds the registered delegate and
    /// skips code generation entirely.
    ///
    /// Generate the C# with AotGenerator on a desktop build, add the generated file to
    /// the app, and call its RegisterAll() during startup -- before the script runs.
    /// </summary>
    public static class PrecompiledRegistry
    {
        static readonly Dictionary<string, PrecompiledFunction> s_functions =
            new Dictionary<string, PrecompiledFunction>(StringComparer.OrdinalIgnoreCase);
        static readonly object s_lock = new object();

        public static void Register(string functionName, PrecompiledFunction implementation)
        {
            if (string.IsNullOrWhiteSpace(functionName) || implementation == null)
            {
                throw new ArgumentException("A precompiled function needs both a name and an implementation.");
            }
            lock (s_lock) { s_functions[functionName] = implementation; }
        }

        public static bool TryGet(string functionName, out PrecompiledFunction implementation)
        {
            lock (s_lock) { return s_functions.TryGetValue(functionName, out implementation); }
        }

        public static bool Contains(string functionName)
        {
            lock (s_lock) { return s_functions.ContainsKey(functionName); }
        }

        public static IReadOnlyCollection<string> RegisteredNames
        {
            get { lock (s_lock) { return new List<string>(s_functions.Keys); } }
        }

        public static void Clear()
        {
            lock (s_lock) { s_functions.Clear(); }
        }
    }

    /// <summary>
    /// Collects the C# that the precompiler generates for each cfunction and writes it
    /// out as a single compilable source file.
    ///
    /// Run this on a desktop build, where runtime compilation works: the script executes
    /// exactly as it normally would, and the generated C# is captured as a side effect.
    /// </summary>
    public static class AotGenerator
    {
        static readonly List<KeyValuePair<string, string>> s_generated =
            new List<KeyValuePair<string, string>>();
        static readonly object s_lock = new object();

        /// <summary>When true, every compiled cfunction also records its generated C#.</summary>
        public static bool Collecting { get; set; }

        internal static void Collect(string functionName, string csharpCode)
        {
            if (string.IsNullOrWhiteSpace(csharpCode))
            {
                return;
            }
            lock (s_lock)
            {
                s_generated.RemoveAll(p => p.Key == functionName);
                s_generated.Add(new KeyValuePair<string, string>(functionName, csharpCode));
            }
        }

        public static void Clear()
        {
            lock (s_lock) { s_generated.Clear(); }
        }

        public static int Count
        {
            get { lock (s_lock) { return s_generated.Count; } }
        }

        /// <summary>Builds the source file holding every collected cfunction.</summary>
        public static string GetSource(string className = "CscsPrecompiled",
                                       string namespaceName = "SplitAndMerge")
        {
            List<KeyValuePair<string, string>> generated;
            lock (s_lock) { generated = new List<KeyValuePair<string, string>>(s_generated); }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated from CSCS cfunction declarations by AotGenerator.");
            sb.AppendLine("//     Call " + className + ".RegisterAll() before running the script.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System; using System.Collections; using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Specialized; using System.Globalization; using System.Linq;");
            sb.AppendLine("using System.Linq.Expressions; using System.Reflection; using System.Text;");
            sb.AppendLine("using System.Threading; using System.Threading.Tasks;");
            sb.AppendLine("using SplitAndMerge;");
            foreach (var ns in Precompiler.Namespaces)
            {
                var line = ns.Trim();
                if (!line.StartsWith("using ")) line = "using " + line;
                if (!line.EndsWith(";")) line += ";";
                sb.AppendLine(line);
            }
            sb.AppendLine();
            sb.AppendLine("namespace " + namespaceName + " {");
            sb.AppendLine("  public static partial class " + className + " {");

            foreach (var def in Precompiler.Definitions)
            {
                var line = def.Trim();
                if (!line.StartsWith("static ") && !line.Contains(" static ")) line = "static " + line;
                if (!line.EndsWith(";")) line += ";";
                sb.AppendLine("    " + line);
            }

            foreach (var pair in generated)
            {
                sb.AppendLine();
                sb.AppendLine(pair.Value);
            }

            sb.AppendLine();
            sb.AppendLine("    public static void RegisterAll() {");
            foreach (var pair in generated)
            {
                sb.AppendLine("      PrecompiledRegistry.Register(\"" + pair.Key + "\", " + pair.Key + ");");
            }
            sb.AppendLine("    }");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Writes GetSource() to disk and returns the path written.</summary>
        public static string WriteSource(string path, string className = "CscsPrecompiled",
                                         string namespaceName = "SplitAndMerge")
        {
            var full = Path.IsPathRooted(path) ? path :
                Path.Combine(Directory.GetCurrentDirectory(), path);
            var dir = Path.GetDirectoryName(full);
            if (!string.IsNullOrWhiteSpace(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(full, GetSource(className, namespaceName));
            return full;
        }
    }
}
