<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>false</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../cscs/*.cs" LinkBase="" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="../cscs/Main.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="9.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>

</Project>